server.port=8081

spring.datasource.url=jdbc:postgresql://ep-lingering-glade-ayjnwn2s-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AFw3UJuqz7tE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=data

spring.datasource.hikari.connection-init-sql=SET search_path TO data


auth.jwt.secret=${AUTH_JWT_SECRET:medical-consult-development-secret-key-2026}
auth.jwt.issuer=${AUTH_JWT_ISSUER:mcsv-auth}
auth.jwt.expiration-seconds=${AUTH_JWT_EXPIRATION_SECONDS:3600}
